# Generated by Django 2.1.5 on 2019-09-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='code_link',
            field=models.URLField(null=True),
        ),
    ]
