# Generated by Django 2.1.5 on 2019-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20191013_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/prog'),
        ),
    ]
